spring:
  datasource:
    url: jdbc:mysql://localhost:3306/123
    username: root
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true